server:
  port: 8762

spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
      server:
        webflux:
          routes:
            - id: parking-service
              uri: http://localhost:8082/
              predicates:
                - Path=/api/v1/parking-service/**

            - id: payment-service
              uri: http://localhost:8085/
              predicates:
                - Path=/api/payments/**

            - id: parking-service
              uri: http://localhost:8084/
              predicates:
                - Path=/api/parking/**


            - id: parking-service
              uri: http://localhost:8083/
              predicates:
                - Path=/api/parking/**
    config:
      enabled: false
      import-check:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
