server:
  port: 8762

spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
      server:
        webflux:
          routes:
            - id: product-service # Kamathi unique ID ekak denna
              uri: http://localhost:8081
              # uri: lb://PRODUCT_SERVICE
              predicates:
                - Path=/product-service/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
